
[workspace]
members = ["crates/lexer", "crates/parser", "crates/syntax"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
authors = ["Your Name <you@example.com>"]

[workspace.dependencies]
# put shared deps here später (im, thiserror, etc.)
