[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[features]
spans = [] # enable to include byte spans in AST nodes

[dependencies]
syntax = { path = "../syntax" }
lexer  = { path = "../lexer" }